# Generated by Django 5.0.6 on 2024-07-09 09:35

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospitalDetails", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DoctorDetail",
            fields=[
                ("doctor_id", models.AutoField(primary_key=True, serialize=False)),
                ("doctor_name", models.CharField(max_length=20)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "availability_days",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("SUN", "Sunday"),
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                            ("SAT", "Saturday"),
                        ],
                        help_text="Select multiple days using Ctrl or Cmd key",
                        max_length=14,
                        null=True,
                    ),
                ),
                (
                    "consultation_hours",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "contact_no",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Contact number must be exactly 9 digits.",
                                regex="^\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "departments",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to="doctorDetails.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospitalDetails.hospitaldetail",
                    ),
                ),
            ],
            options={
                "ordering": ["doctor_id"],
            },
        ),
    ]
