# Generated by Django 5.0.6 on 2024-07-01 16:48

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospitalDetails", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorDetail",
            fields=[
                ("doctor_id", models.AutoField(primary_key=True, serialize=False)),
                ("department", models.CharField(max_length=50)),
                ("doctor_name", models.CharField(max_length=20)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "availability_days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "consultation_hours",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "contact_no",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                (
                    "hospital_id",
                    models.ForeignKey(
                        db_column="hospital_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospitalDetails.hospitaldetail",
                    ),
                ),
            ],
            options={
                "unique_together": {("doctor_id", "hospital_id", "department")},
            },
        ),
    ]
