# Generated by Django 5.0.6 on 2024-07-10 18:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("healthInsurance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(blank=True, max_length=20, null=True)),
                ("age", models.IntegerField()),
                ("relation", models.CharField(max_length=15)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Divorced", "Divorced"),
                            ("Widowed", "Widowed"),
                            ("Separated", "Separated"),
                            ("Committed", "Committed"),
                            ("Other", "Other"),
                        ],
                        max_length=25,
                    ),
                ),
                ("profession", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "contact_no",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Contact number must be exactly 9 digits.",
                                regex="^\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "health_insurance_card_no",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="healthInsurance",
                        to="healthInsurance.healthinsurancecard",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Family Member Details",
                "ordering": ["health_insurance_card_no"],
            },
        ),
        migrations.AddConstraint(
            model_name="familymember",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "marital_status__in",
                        [
                            "Single",
                            "Married",
                            "Divorced",
                            "Widowed",
                            "Separated",
                            "Committed",
                            "Other",
                        ],
                    )
                ),
                name="check_marital_status_valid",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="familymember",
            unique_together={("health_insurance_card_no", "first_name", "relation")},
        ),
    ]
