# Generated by Django 5.0.6 on 2024-06-29 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "healthInsurance",
            "0002_remove_healthinsurancecard_unique_health_insurance_card_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(blank=True, max_length=20, null=True)),
                ("age", models.IntegerField()),
                ("relation", models.CharField(max_length=15)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=10
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Divorced", "Divorced"),
                            ("Widowed", "Widowed"),
                            ("Separated", "Separated"),
                            ("Committed", "Committed"),
                            ("Other", "Other"),
                        ],
                        max_length=25,
                    ),
                ),
                ("profession", models.CharField(blank=True, max_length=20, null=True)),
                ("contact_no", models.CharField(max_length=15, unique=True)),
                (
                    "health_insurance_card_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthInsurance.healthinsurancecard",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="familymember",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "marital_status__in",
                        [
                            "Single",
                            "Married",
                            "Divorced",
                            "Widowed",
                            "Separated",
                            "Committed",
                            "Other",
                        ],
                    )
                ),
                name="check_marital_status_valid",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="familymember",
            unique_together={("health_insurance_card_no", "first_name", "relation")},
        ),
    ]
