# Generated by Django 5.0.6 on 2024-06-30 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("healthInsurance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildrenCheckUp",
            fields=[
                ("check_up_id", models.AutoField(primary_key=True, serialize=False)),
                ("parents_name", models.CharField(max_length=50)),
                (
                    "number_of_children",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("children_name_and_age", models.JSONField(blank=True, null=True)),
                ("vaccination_completed", models.JSONField(blank=True, null=True)),
                ("date_of_vaccination", models.JSONField(blank=True, null=True)),
                ("vaccination_name", models.JSONField(blank=True, null=True)),
                (
                    "health_insurance_card_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthInsurance.healthinsurancecard",
                    ),
                ),
            ],
            options={
                "unique_together": {("health_insurance_card_no", "parents_name")},
            },
        ),
    ]
