# Generated by Django 5.0.6 on 2024-06-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yearlyCheckup", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yearlycheckup",
            name="date_of_check_up",
            field=models.DateField(blank=True, null=True),
        ),
    ]
