# Generated by Django 5.0.6 on 2024-07-01 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthInsurance", "0001_initial"),
        ("yearlyCheckup", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="yearlycheckup",
            name="check_date_of_check_up_valid",
        ),
        migrations.AddConstraint(
            model_name="yearlycheckup",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date_of_check_up__isnull", True),
                    ("date_of_check_up__lte", datetime.date(2024, 7, 1)),
                    _connector="OR",
                ),
                name="check_date_of_check_up_valid",
            ),
        ),
    ]
