# Generated by Django 5.0.6 on 2024-07-18 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("familyMember", "0001_initial"),
        (
            "yearlyCheckup",
            "0002_remove_yearlycheckup_check_date_of_check_up_valid_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="yearlycheckup",
            name="check_date_of_check_up_valid",
        ),
        migrations.AddConstraint(
            model_name="yearlycheckup",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date_of_check_up__isnull", True),
                    ("date_of_check_up__lte", datetime.date(2024, 7, 18)),
                    _connector="OR",
                ),
                name="check_date_of_check_up_valid",
            ),
        ),
    ]
