# Generated by Django 5.0.6 on 2024-06-29 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "healthInsurance",
            "0002_remove_healthinsurancecard_unique_health_insurance_card_and_more",
        ),
        ("yearlyCheckup", "0002_alter_yearlycheckup_date_of_check_up"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="yearlycheckup",
            name="check_date_of_check_up_valid",
        ),
        migrations.AlterField(
            model_name="yearlycheckup",
            name="yearly_check_up_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="yearlycheckup",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date_of_check_up__isnull", True),
                    ("date_of_check_up__lte", datetime.date(2024, 6, 29)),
                    _connector="OR",
                ),
                name="check_date_of_check_up_valid",
            ),
        ),
    ]
