# Generated by Django 5.0.6 on 2024-06-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthInsuranceCard",
            fields=[
                (
                    "health_insurance_card_no",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("expiry_date_of_card", models.DateField()),
            ],
        ),
    ]
