# Generated by Django 5.0.6 on 2024-06-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("healthInsurance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="healthinsurancecard",
            name="unique_health_insurance_card",
        ),
        migrations.AlterUniqueTogether(
            name="healthinsurancecard",
            unique_together=set(),
        ),
    ]
