# Generated by Django 5.0.6 on 2024-07-18 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("familyMedicalDetails", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=50)),
                (
                    "price_per_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("INR", "Indian Rupee"),
                            ("GBP", "British Pound"),
                        ],
                        default="EUR",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Medicines",
            },
        ),
        migrations.CreateModel(
            name="MedicalExpensesDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "family_medical_detail",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_expenses_detail",
                        to="familyMedicalDetails.familymedicaldetail",
                    ),
                ),
                (
                    "medicine_prescribed",
                    models.ManyToManyField(
                        related_name="medical_expenses_details",
                        to="medicalExpenseDetails.medicines",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Medical Expenses Details",
            },
        ),
        migrations.CreateModel(
            name="MedicalBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="medical_bills/"
                    ),
                ),
                (
                    "medical_expenses_detail",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_bill",
                        to="medicalExpenseDetails.medicalexpensesdetail",
                    ),
                ),
            ],
        ),
    ]
