# Generated by Django 5.0.6 on 2024-07-01 16:55

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctorDetails", "0001_initial"),
        ("healthInsurance", "0001_initial"),
        ("hospitalDetails", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyMedicalDetail",
            fields=[
                ("visit_id", models.AutoField(primary_key=True, serialize=False)),
                ("date_of_visit", models.DateTimeField()),
                ("symptoms", models.TextField(blank=True, null=True)),
                ("diagnosis", models.TextField(blank=True, null=True)),
                ("medication", models.TextField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        db_column="department",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_visits",
                        to="doctorDetails.doctordetail",
                    ),
                ),
                (
                    "doctor_id",
                    models.ForeignKey(
                        db_column="doctor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_visits",
                        to="doctorDetails.doctordetail",
                    ),
                ),
                (
                    "health_insurance_card_no",
                    models.ForeignKey(
                        db_column="health_insurance_card_no",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthInsurance.healthinsurancecard",
                    ),
                ),
                (
                    "hospital_id",
                    models.ForeignKey(
                        db_column="hospital_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_visits",
                        to="hospitalDetails.hospitaldetail",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="familymedicaldetail",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date_of_visit__lte", django.db.models.functions.datetime.Now())
                ),
                name="date_of_visit_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="familymedicaldetail",
            constraint=models.UniqueConstraint(
                fields=(
                    "health_insurance_card_no",
                    "doctor_id",
                    "hospital_id",
                    "department",
                    "date_of_visit",
                ),
                name="unique_doctor_visit",
            ),
        ),
    ]
