# Generated by Django 5.0.6 on 2024-07-18 20:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctorDetails", "0001_initial"),
        ("familyMember", "0001_initial"),
        ("healthInsurance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyMedicalDetail",
            fields=[
                ("visit_id", models.AutoField(primary_key=True, serialize=False)),
                ("date_of_visit", models.DateField()),
                ("symptoms", models.TextField(blank=True, null=True)),
                ("diagnosis", models.TextField(blank=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        db_column="doctor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_visits",
                        to="doctorDetails.doctordetail",
                    ),
                ),
                (
                    "health_insurance_card_no",
                    models.ForeignKey(
                        db_column="health_insurance_card_no",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthInsurance.healthinsurancecard",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        db_column="family_member_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_details",
                        to="familyMember.familymember",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Family Medical History",
                "db_table": "family_medical",
            },
        ),
        migrations.AddConstraint(
            model_name="familymedicaldetail",
            constraint=models.UniqueConstraint(
                fields=(
                    "health_insurance_card_no",
                    "name",
                    "doctor_id",
                    "date_of_visit",
                ),
                name="unique_doctor_visit",
            ),
        ),
        migrations.AddConstraint(
            model_name="familymedicaldetail",
            constraint=models.CheckConstraint(
                check=models.Q(("date_of_visit__lte", datetime.date(2024, 7, 18))),
                name="Date of visit cannot be future date",
            ),
        ),
    ]
